/**
 * The shapes the page reads. These mirror `fixtures/manifest.json`, which is
 * GENERATED by `scripts/assess-fixtures.ts` and never edited by hand.
 *
 * THE EXTENSION SEAM THAT MATTERS (v2 / v3). `provenance` already admits a
 * `captured` class, and `EstimatorRecord`/`Assessment` have the same shape
 * whether a figure came from a pinned native run or from a live engine. So a
 * real capture (v2) drops into the same manifest with no UI change, and a
 * browser engine (v3) replaces the `assessment: null` state with a live run
 * without the display learning a second vocabulary.
 */

/** Where a file's bytes came from. Badged persistently, never colour-only. */
export type Provenance =
  // A software model of the circuit. Not hardware. v1 ships only these...
  | 'simulated'
  // ...and these: streams defined by a published construction.
  | 'deterministic'
  // [extension] point — v2: a real capture from the device.
  | 'captured'
  // A visitor's own bytes, or a fixture they edited in the browser.
  | 'modified';

export interface SampleEncoding {
  bitsPerSymbol: number;
  sampleCount: number;
  shippedForm: 'packed-bits' | 'one-sample-per-byte';
  bitOrder: 'msb-first' | 'lsb-first' | 'n/a';
  /** The exact command that converts the shipped file to what the tool reads. */
  conversion: string;
  /** Dropped, padded, rejected, or why the question does not arise. */
  incompleteFinalSample: string;
  originalBytes: number;
  originalSha256: string;
  convertedBytes: number;
  convertedSha256: string;
}

export interface EstimatorRecord {
  name: string;
  /** Bits of min-entropy per sample, in the declared symbol width. */
  bitsPerSample: number | null;
  /** Bits of min-entropy per bit, from the bit-string branch. */
  bitsPerBit: number | null;
  /** The standard defines this estimator for binary inputs only. */
  bitstringOnly: boolean;
  /** A branch that should have reported a value did not. */
  declined: boolean;
  /** The modelling assumption, read from the standard. Prose, not a measurement. */
  assumption: string;
}

export interface AssessmentTool {
  program: string;
  toolVersion: string;
  forkRepo: string;
  forkCommit: string;
  upstreamBaseline: string;
  patched: true;
  patchedBuildNote: string;
}

export interface Assessment {
  tool: AssessmentTool;
  platform: string;
  command: string;
  exitCode: number;
  errorLevel: number;
  errorMessage: string | null;
  /** The SHA-256 the TOOL hashed. Invariant I1 compares it to the file's own. */
  toolSha256: string;
  bitsPerSymbol: number;
  bitsPerSymbolInferred: boolean;
  estimators: EstimatorRecord[];
  overall: {
    hOriginal: number | null;
    hBitstring: number | null;
    hAssessed: number | null;
    dataWordSize: number | null;
    /** Derived: hAssessed / dataWordSize. Labelled as derived wherever shown. */
    assessedBitsPerBit: number | null;
  } | null;
  partial: boolean;
  belowMinimum: boolean;
}

export interface Fixture {
  id: string;
  title: string;
  blurb: string;
  act: number;
  provenance: Provenance;
  neverASecret: boolean;
  variantOf: string | null;
  seed: number | null;
  generator: string;
  procedure: string;
  encoding: SampleEncoding;
  download: string;
  /**
   * null means NO ASSESSMENT EXISTS for these bytes, and the page says so
   * rather than borrowing a number from somewhere else (invariant I1).
   * [extension] point — v3 replaces this state with a live engine run.
   */
  assessment: Assessment | null;
}

export interface Manifest {
  schemaVersion: number;
  sampleMinimum: number;
  fixtures: Fixture[];
}
